### ISSUE TITLE
[Bug] Water bullets pop tires and deal damage value to parts and vehicles

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1384]

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.

**Comment by LauraDarkez** [comment]
bug not fixed. still kills vehicles and pops tires in official release

**Comment by LauraDarkez** [comment]
![2022-12-05_00 37 26](https://user-images.githubusercontent.com/53153740/205557705-678d672a-79da-47c3-8659-df2340e929a0.png)

**Comment by DonBruce64** [comment]
It would appear Elephant marked himself as the "Assigned" person without yet fixing the bug.  That confused me, as when bugs get fixed, I "Assign" them to the person who fixed them.  Re-opened.

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
