### ISSUE TITLE
v16.1 steal vehicle in multiplayer

### ISSUE THREAD

**Issue by dentesdracula** [DonBruce64/MinecraftTransportSimulator#322]
Hello . In multiplayer, player A owns a car, player B craft a new key and can unlock player A's car and steal it.
Thank you for mod

**Comment by boot2big** [comment]
Has Player A tried shift clicking his car with a key after pairing the key to the car by normally clicking on it? Doing so will make it so that Player B, Player J and even Player X can't take parts off of it or make new keys for it.

**Comment by dentesdracula** [comment]
Yes, we have done all these tests and player B has just re-craft a new key and player B can open a vehicle already closed by player A

**Comment by DonBruce64** [comment]
What do you mean by re-craft a key?  Please detail the exact steps and every step you take with the keys.  From the point you place down the vehicle, to the point you have your issue.

**Comment by boot2big** [comment]
I just tested this myself, they're saying it's possible to bypass security by linking a new key to a car, even if it's owned and shouldn't be possible

**Comment by DonBruce64** [comment]
Ah, and you can confirm that even if a vehicle is owned you can right-click the vehicle with a new key and you then get a key that works on that vehicle and can open it?

**Comment by dentesdracula** [comment]
1 Have each placed our vehicle 
2 We each craft our key (a two iron string) 
3 We click with the key on our vehicle for the locker 
4 We test our keys on the two vehicles, and of course the keys do not allow to open the vehicle that does not belong to us. 
5 We craft a new key to try to open the vehicle that is not ours, and the key allows to close and open the vehicle that is not ours.

Thank you and 
Sorry for my english google trad ;-)

**Comment by dentesdracula** [comment]
> Ah, et vous pouvez confirmer que même si un véhicule appartient, vous pouvez cliquer avec le bouton droit sur le véhicule avec une nouvelle clé et vous obtenez alors une clé qui fonctionne sur ce véhicule et pouvez l'ouvrir?



> Ah, and you can confirm that even if a vehicle is owned you can right-click the vehicle with a new key and you then get a key that works on that vehicle and can open it?

Yes i confirm :-)

**Comment by DonBruce64** [comment]
Rodger that.  I'm well overdue for some major changes to how vehicle interaction is done, so expect this to come around in a few cycles.  I first need to shore up the bug that got caused by the instrument key fix, and if I can't get this one fixed in that cycle, I'll have to push it till after I get the instruments fixed.

**Comment by dentesdracula** [comment]
> Rodger that. I'm well overdue for some major changes to how vehicle interaction is done, so expect this to come around in a few cycles. I first need to shore up the bug that got caused by the instrument key fix, and if I can't get this one fixed in that cycle, I'll have to push it till after I get the instruments fixed.


Your mod is so cool that we will have to wait :-)
Thank you

**Comment by DonBruce64** [comment]
So when you use the new key, do you get a message about you not being the owner?  And after that message, are you able to still unlock the vehicle with that new key?

**Comment by boot2big** [comment]
When testing this yes, it did toss a message saying it was not my vehicle. And then I could unlock the car with said key.

**Comment by DonBruce64** [comment]
Yup.  That makes sense with what I saw in my code.  If y'all could test V16.1.1 I think it's fixed in there.

**Comment by dentesdracula** [comment]
Hello I have just redone the tests with version 16.1.1 and the problem is still there.
For info there is no owner's message with the new key. The vehicle always unlocks with a new key. Sorry

**Comment by dentesdracula** [comment]
P.S Right clicking with the wrench no longer crashes my server ;-)

**Comment by dentesdracula** [comment]
> Lors du test de ce oui, il a lancé un message disant que ce n'était pas mon véhicule. Et puis j'ai pu déverrouiller la voiture avec cette clé.
> (Je ne pouvais cependant pas changer de propriétaire.)


With my tests I didn’t get this message. We have just locked and unlocked vehicle message

**Comment by dentesdracula** [comment]
Sorry I did the test again is all ok
sorry

**Comment by dentesdracula** [comment]
The vehicle locks correctly now and only the owner can access it Just to add that we should not be able to break the wheels of a vehicle that does not belong to us
Thank you for your responsiveness and for being super mod

**Comment by DonBruce64** [comment]
You're welcome!  As to the wheel breakage, as mentioned in #324 that's per design as that's vehicle damage, and that can be inflicted by anyone on any vehicle regardless of ownership.  Would be really odd if you shot a vehicle with a gun and you could only damage it if you were the owner.
