### ISSUE TITLE
[Bug]Crash when a seat placed to a turret

### ISSUE THREAD

**Issue by ym1025** [DonBruce64/MinecraftTransportSimulator#690]
As avobe
Crash report: 
[crash-2021-01-23_17.15.00-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5859920/crash-2021-01-23_17.15.00-client.txt)

IV version: Immersive Vehicles-1.12.2-19.13.1.jar
Forge version: 14.23.5.2854
Content pack: UNU Military Pack [MTS] 1.12.2-18.0.0-3.5.1.jar, UNU Parts Pack [MTS] 1.12.2-19.12.0-4.0.0-BETA.jar

**Comment by DonBruce64** [comment]
Does this happen all the time, or every once and a while?

**Comment by DonBruce64** [comment]
Should be fixed in V19.14.0.

**Comment by ym1025** [comment]
It's not fixed.
Crash report: 
[crash-2021-01-26_17.38.52-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5872163/crash-2021-01-26_17.38.52-client.txt)
[crash-2021-01-26_17.38.27-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5872165/crash-2021-01-26_17.38.27-client.txt)

Immersive vehicles version: Immersive Vehicles-1.12.2-19.14.0.jar
Forge version: 14.23.5.2854
Content pack: Automobilwerke_Schwikau_VEB_1970.jar, Miszko's_Vehicle_Pack_06.jar, UNU Civilian Pack [MTS] 1.12.2-19.13.0-4.0.0.jar, UNU Military Pack [MTS] 1.12.2-18.0.0-3.5.1.jar, UNU Parts Pack [MTS] 1.12.2-19.13.0-4.0.1.jar, Spitfire_Pack_1.12.2-1.3.0.jar

**Comment by Jimmy805** [comment]
Probably because UNU Military Pack hasn't been updated to V4 yet.

**Comment by DonBruce64** [comment]
Not a UNU issue.  This is due to the code itself.

**Comment by DonBruce64** [comment]
Fixed for sure as of V19.15.0.
